# Copyright (C) 2024 Eternilab <support@eternilab.com>
#
# SPDX-License-Identifier: MIT

---

- name: "Be sure debsums is installed (APT based)"
  ansible.builtin.apt:
    pkg: 'debsums'
    state: present
  when: ansible_pkg_mgr == 'apt'
  become: true
  tags:
    - install

- name: "Be sure debsums is configured"
  ansible.builtin.template:
    src: debsums.j2
    dest: /etc/default/debsums
    mode: '0644'
  become: true
  tags:
    - conf
